sudo: required #we need super user permissions to execute this build
services:
  - docker

before_install:
  - docker build -t mephianna/docker-react -f Dockerfile.dev .

script:
  - docker run mephianna/docker-react npm run test -- --coverage --watchAll=false