sudo: required #we need super user permissions to execute this build
services:
  - docker

before_install:
  - docker build -f -t mephianna/docker-react Dockerfile.dev .

script:
  - docker run mephianna/docker-react npm run test -- --coverage